import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <nav className="bg-gray-800 p-4 mb-8">
            <div className="max-w-6xl mx-auto flex items-center space-x-6">
              <a href="/" className="text-white font-semibold hover:underline">Home</a>
              <a href="/admin-dashboard" className="text-white font-semibold hover:underline">Admin Dashboard</a>
            </div>
          </nav>
          {children}
      </body>
    </html>
  );
}
